Added card number masking function
fintech-kotlin/petrov-cashback-service pull request #1
Opened 2020-02-22 10:49 UTC by al3ks3y

# Выполнено задание №1

## В процесс было сделано:
 - Реализован маскировщик номера карты клиента
 - Создан работающий генератор уведомлений клиенту

## PR чеклист:
 - [ ] В Project выставлен `Tinkoff "Java to Kotlin"`
 - [ ] Добавлен label с номером домашнего задания

2020-02-22 11:11 UTC, al3ks3y commented
Task 1 completed with the creation of a card disguiser and a client notificator

2020-02-24 15:12 UTC, otpt commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +        result.append("начислен cashback в размере " + notificationMessageInfo.cashback + "\n")
можно проще : result.append("начислен cashback в размере ${notificationMessageInfo.cashback}\n")

2020-02-24 19:46 UTC, al3ks3y commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +        result.append("начислен cashback в размере " + notificationMessageInfo.cashback + "\n")
> можно проще : result.append("начислен cashback в размере ${notificationMessageInfo.cashback}\n")

Согласен, можно и через $

2020-02-25 09:17 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        var result:MutableList<Char> = cardNumber.toMutableList()
+ Явное указание типа для переменной result не требуется, Kotlin в таком кейсе легко сам выведет тип, а Idea его подсветит.
+ Переменная result может быть read-only. В Kotlin в принципе хорошая практика по умолчанию делать все переменный read-only и только при необходимости уже менять их на var.

2020-02-25 09:21 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        if(result.size>=end&&start>=0){
В Kotlin работа со структурами данных расширена огромным количеством функций расширений. Сейчас блок if else выглядит сложно читаемым и избыточным. Взгляни на такие функции расширения как forEachIndexed/mapIndexed, они должны помочь тебе упростить код имплементации.

2020-02-25 09:22 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/CardNumberMaskerImpl.kt
> +        return result.toString().replace(", ","").replace("[","").replace("]","")
Код рабочий, но опять слишком много операция заставляют всматриваться чтобы понять что именно мы хотим сделать. joinToString лучший друг в таких ситуациях.

2020-02-25 11:42 UTC, ArtyomIvanov requested changes

2020-02-25 11:42 UTC, ArtyomIvanov commented on src/main/kotlin/ru/tinkoff/fintech/service/notification/NotificationMessageGeneratorImpl.kt
> +        var result:StringBuilder=StringBuilder("Уважаемый, ")
Многострочный текст можно создать, используя тройные кавычки. Больше нам не нужны символы перевода строки \n, а также символы типа \t, \b, \r и т.д. StringBuilder тогда тоже будет не нужен.

2020-03-02 10:03 UTC, ArtyomIvanov approved these changes
Можно мерджить.

2020-03-03 03:45 UTC, merged